language: groovy
jdk:
  - oraclejdk7
  - oraclejdk8
env:
  global:
    - TERM=dumb
sudo: false
before_install:
  - curl http://haxe.org/website-content/downloads/3,1,3/downloads/haxe-3.1.3-linux64.tar.gz | tar xz
  - export PATH=$PATH:$PWD/haxe-3.1.3
  - export HAXE_HOME=$PWD/haxe-3.1.3
  - export HAXE_STD_PATH=$PWD/haxe-3.1.3/std
  - haxe -version
